theme = "ww"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "The Chronicles of the Wandering Wolves"

[build]
  writeStats = true

[permalinks]
  entries = "/entries/:slug/"

[taxonomies]
  session = "sessions"
