theme = "ww"
baseURL = "http://www.wandering-wolves.co.uk/"
languageCode = "en-us"
title = "The Chronicles of the Wandering Wolves"

[build]
  writeStats = true

[permalinks]
  entries = "/entries/:slug/"
  locations = "/locations/:slug/"

[taxonomies]
  session = "sessions"
  place = "places"
