theme = "ww"
baseURL = "https://www.wandering-wolves.co.uk/"
languageCode = "en-us"
title = "The Chronicles of the Wandering Wolves"

[build]
  writeStats = true

[permalinks]
  entries = "/entries/:slug/"
  locations = "/locations/:slug/"

[taxonomies]
  session = "sessions"
  place = "places"
  group = "groups"
  org = "orgs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"
